name = "denot"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Denot"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "main"

[[lean_lib]]
name = "Denot"
